[build]
  builder = "nixpacks"
  [build.config]
    installCommand = "npm install --include=optional"
    buildCommand = "npx next build"
    nixPkgs = ["nodejs_22"]

[deploy]
  healthcheckPath = "/health"
  startCommand = "npm start"

[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_PRODUCTION = "false"
